function Wout = WarpFuncSinAbs(dx,dy,in3)
%WARPFUNC
%    WOUT = WARPFUNC(DX,DY,IN3)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    18-Oct-2017 12:13:08

P1 = in3(:,1);
P2 = in3(:,2);
P3 = in3(:,3);
P4 = in3(:,4);
Wout = [P1+dx+P2.*sin(abs(dx).*(2.0./7.1e1)),P3+dy+P4.*sin(abs(dy).*(2.0./7.1e1))];
